### ISSUE TITLE
Input file error handling

### ISSUE THREAD

**Issue by Eto322** [sandders/euro-diffusion#4]
``` python 
def parse_cases(filename):
    with open(filename, 'r') as file:
        country_count = int(file.readline())

        cases = []

        while country_count:
            if not 1 <= country_count <= 20:
                print('Error: The number of countries (1 ≤ c ≤ 20)')
                return None

            lines = []

            for i in range(country_count):
                lines.append(file.readline())

            cases.append(lines)

            country_count = int(file.readline())

        return cases
```

In the parse_cases() function reads input from the file and returns a list of cases. However, it assumes that the input file is formatted correctly and contains the expected number of lines for each case. If the input file is malformed or the number of lines for a case is incorrect, it may result in unexpected behavior or errors. It would be beneficial to add some error handling or validation logic to ensure the input file is correctly formatted.

**Comment by sandders** [comment]
Fixed in https://github.com/sandders/euro-diffusion/pull/6
